name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven test 
        run: mvn test
      
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Check org both spellings
        run: |
          echo "ORG1=${{ secrets.SONAR_ORGANIZATION != '' }}"
          echo "ORG2=${{ secrets.SONAR_ORGINIZATION != '' }}"



      - name: Check secrets availability
        run: |
          echo "has_org=${{ secrets.SONAR_ORGANIZATION != '' }}"
          echo "has_key=${{ secrets.SONAR_PROJECT_KEY != '' }}"
          echo "has_url=${{ secrets.SONAR_URL != '' }}"
          echo "has_token=${{ secrets.SONAR_TOKEN != '' }}"



      - name: Debug Sonar
        run: |
          echo "ORG=${{ secrets.SONAR_ORGINIZATION }}"
          echo "KEY=${{ secrets.SONAR_PROJECT_KEY }}"
          echo "URL=${{ secrets.SONAR_URL }}"


      # Setup java 11 to be default (sonar-scanner requirement as of 5.x)
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # See 'Supported distributions' section
          java-version: '11'
 


      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=${{ secrets.SONAR_URL }}
            -Dsonar.organization=${{ secrets.SONAR_ORGINIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=.
